#!/usr/bin/env node
/* STRATA — GNU GPL v2. 条文は LICENSE、由来は NOTICE.md。 */
// -*- coding: utf-8 -*-
/**
 * 参照表の自動生成 (docs/06 §6.1, §6.7)。
 *
 *   node tools/gen_reference.js           docs/reference/*.md を生成
 *   node tools/gen_reference.js --check    再生成して差分が出たら落とす
 *   node tools/gen_reference.js --spoiler 3   出す情報の上限 (既定 3 = 完全)
 *
 * ★正本は src/data/*.json。**この出力を手で編集しないこと。**
 *   docs に数値の一覧を手書きしないための仕組み ([[D-15]])。
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'docs', 'reference');
const DATA_DIR = path.join(ROOT, 'src', 'data');

const argv = process.argv.slice(2);
const CHECK = argv.includes('--check');
const SPOILER = (() => {
  const i = argv.indexOf('--spoiler');
  return i !== -1 ? parseInt(argv[i + 1], 10) : 3;
})();

function load(name) {
  const p = path.join(DATA_DIR, name + '.json');
  const o = JSON.parse(fs.readFileSync(p, 'utf8'));
  return { entries: o.entries || o, raw: o };
}

const D = {
  monsterBase: load('monster-base'), monsters: load('monsters'),
  itemBase: load('item-base'), items: load('items'),
  lineages: load('lineages'), roles: load('roles'),
  abilities: load('abilities'), sigils: load('sigils'),
  egos: load('egos'), uniques: load('uniques'),
  rooms: load('rooms'), vaults: load('vaults')
};

const byId = list => Object.fromEntries(list.map(e => [e.id, e]));
const MB = byId(D.monsterBase.entries);
const IB = byId(D.itemBase.entries);
const SG = byId(D.sigils.entries);

/** spoiler レベルで絞る。既定は 3(完全)。 */
const visible = e => (e.spoiler || 1) <= SPOILER;

function banner(source) {
  return `<!-- GENERATED by tools/gen_reference.js — DO NOT EDIT. 正本: ${source} -->`;
}

function table(headers, rows) {
  const out = ['| ' + headers.join(' | ') + ' |',
               '|' + headers.map(() => '---').join('|') + '|'];
  for (const r of rows) out.push('| ' + r.join(' | ') + ' |');
  return out.join('\n');
}

const esc = s => String(s === undefined || s === null ? '' : s).replace(/\|/g, '\\|');
const dice = s => (s ? '`' + s + '`' : '—');
const sigilNames = ids => (ids || []).map(id => (SG[id] ? SG[id].name : id)).join(' ') || '—';

/* ---------- 各ページ ---------- */

const pages = {};

pages['monsters.md'] = () => {
  const rows = D.monsters.entries.filter(visible).sort((a, b) => a.depth - b.depth).map(m => [
    esc(m.name), '`' + m.id + '`', MB[m.base] ? MB[m.base].name : m.base,
    m.depth, m.rarity, m.level, dice(m.hp), m.ac,
    (m.speed - 110 >= 0 ? '+' : '') + (m.speed - 110),
    m.sleep === undefined ? '—' : m.sleep,
    m.mexp,
    (m.blows || []).map(b => `${b.method}/${b.effect} ${b.dice}`).join('<br>') || '—',
    (m.flags || []).join(' ') || '—'
  ]);
  return [
    banner('src/data/monsters.json'), '',
    '# 敵一覧', '',
    `全 ${rows.length} 種 (spoiler level ${SPOILER} まで)。深度順。`, '',
    '速度は 110 を +0 とした表示。警戒度(sleep)は小さいほど起きやすい ([[D-40]])。', '',
    table(['名前', 'id', '系統', '深度', '稀少', 'Lv', 'HP', 'AC', '速度', '警戒', 'mexp', '攻撃', 'フラグ'], rows),
    '', '## 系統', '',
    table(['系統', 'id', '記号', '説明'],
      D.monsterBase.entries.filter(visible).map(b => [esc(b.name), '`' + b.id + '`', '`' + b.glyph + '`', esc(b.desc)])),
    ''
  ].join('\n');
};

pages['items.md'] = () => {
  const rows = D.items.entries.filter(visible).sort((a, b) => a.depth - b.depth).map(it => [
    esc(it.name), '`' + it.id + '`', IB[it.base] ? IB[it.base].name : it.base,
    it.depth, it.rarity, it.weight,
    it.dice ? dice(it.dice) : (it.ac !== undefined ? '[' + it.ac + ']' : '—'),
    it.mult ? '×' + it.mult : '—',
    (it.toHit || it.toDam) ? `(${it.toHit || 0},${it.toDam || 0})` : '—',
    it.effect ? '`' + it.effect + '`' : '—',
    it.cost
  ]);
  return [
    banner('src/data/items.json'), '',
    '# アイテム一覧', '',
    `全 ${rows.length} 種 (spoiler level ${SPOILER} まで)。深度順。`, '',
    table(['名前', 'id', '分類', '深度', '稀少', '重量', 'ダイス/AC', '倍率', '(命中,ダメージ)', '効果', '価格'], rows),
    '', '## 分類とスロット', '',
    table(['分類', 'id', '記号', 'スロット', 'スタック'],
      D.itemBase.entries.filter(visible).map(b =>
        [esc(b.name), '`' + b.id + '`', '`' + b.glyph + '`', b.slot || '—', b.stack ? 'する' : 'しない'])),
    ''
  ].join('\n');
};

pages['lineages.md'] = () => {
  const S = ['str', 'int', 'wis', 'dex', 'con', 'chr'];
  const rows = D.lineages.entries.filter(visible).map(l => [
    esc(l.name), '`' + l.id + '`',
    ...S.map(k => (l.stats[k] > 0 ? '+' : '') + l.stats[k]),
    l.hitDie, l.expFactor + '%', l.infra,
    (l.flags || []).join(' ') || '—'
  ]);
  return [
    banner('src/data/lineages.json'), '',
    '# 系統(旧・種族)', '',
    table(['名前', 'id', '体力', '演算', '意志', '反射', '耐久', '統率', 'HD', '経験値', '暗視', 'フラグ'], rows),
    '', '## 技能補正', '',
    table(['名前', '近接', '射撃', '隠密', '知覚', '解錠'],
      D.lineages.entries.filter(visible).map(l =>
        [esc(l.name), l.skills.melee, l.skills.shoot, l.skills.stealth, l.skills.perception, l.skills.disarm])),
    '', '## 説明', '',
    ...D.lineages.entries.filter(visible).map(l => `- **${l.name}** — ${l.desc}`),
    ''
  ].join('\n');
};

pages['roles.md'] = () => {
  const rows = D.roles.entries.filter(visible).map(r => [
    esc(r.name), '`' + r.id + '`',
    r.system || '—', r.spStat || '—', r.hitDie, r.expFactor + '%', r.maxBlows,
    (r.statOrder || []).slice(0, 3).join('>')
  ]);
  return [
    banner('src/data/roles.json'), '',
    '# ロール(旧・職業)', '',
    '能力値は statOrder の上位から 17/16/15/12/11/10 を配る ([[D-41]])。', '',
    table(['名前', 'id', 'サブシステム', '主能力値', 'HD', '経験値', '最大攻撃回数', '能力値優先'], rows),
    '', '## 技能 (基礎 / レベルごとの伸び)', '',
    table(['名前', '近接', '射撃', '隠密', '知覚', '解錠'],
      D.roles.entries.filter(visible).map(r => [esc(r.name),
        `${r.skills.melee} / +${r.skillsPerLevel.melee}`,
        `${r.skills.shoot} / +${r.skillsPerLevel.shoot}`,
        `${r.skills.stealth}`,
        `${r.skills.perception} / +${r.skillsPerLevel.perception}`,
        `${r.skills.disarm} / +${r.skillsPerLevel.disarm}`])),
    '', '## 説明と習得能力', '',
    ...D.roles.entries.filter(visible).map(r =>
      `- **${r.name}** — ${r.desc}\n  - 能力: ${(r.abilities || []).join(', ') || 'なし'}`),
    ''
  ].join('\n');
};

pages['abilities.md'] = () => {
  const SYS = { psi: '精神系', machine: '機械系', bio: '生体系' };
  const rows = D.abilities.entries.filter(visible).sort((a, b) =>
    (a.system + a.level).localeCompare(b.system + b.level) || a.level - b.level).map(a => [
    esc(a.name), '`' + a.id + '`', SYS[a.system] || a.system,
    a.level, a.cost, a.fail + '%', '`' + a.effect + '`', esc(a.desc)
  ]);
  return [
    banner('src/data/abilities.json'), '',
    '# 能力一覧', '',
    '失敗率は基礎値。実際は `基礎 - 3*(Lv - 必要Lv) - 主能力値補正` (docs/02 §2.10)。', '',
    table(['名前', 'id', '系統', '必要Lv', 'コスト', '基礎失敗率', '効果', '説明'], rows),
    ''
  ].join('\n');
};

pages['sigils.md'] = () => {
  const KIND = { stat: '能力値', resist: '耐性', brand: '属性付与', slay: '系統特効', misc: 'その他' };
  const LEARN = { wear: '装備する', hit: '発動する', hurt: '被弾する', analyze: '解析のみ' };
  const rows = D.sigils.entries.filter(visible).map(s => [
    esc(s.name), '`' + s.id + '`', KIND[s.kind] || s.kind,
    s.stat || s.element || s.base || s.attr || '—',
    LEARN[s.learn] || s.learn, s.value, s.taint ? '**汚染**' : '—', esc(s.desc)
  ]);
  return [
    banner('src/data/sigils.json'), '',
    '# 刻印一覧', '',
    '刻印を1つ知ると、以後すべての装備でその刻印が既知になる (docs/02 §2.8)。', '',
    table(['名前', 'id', '種別', '対象', '判明の経路', '価値', '汚染', '説明'], rows),
    ''
  ].join('\n');
};

pages['egos.md'] = () => {
  const rows = D.egos.entries.filter(visible).sort((a, b) => a.depth - b.depth).map(e => [
    esc(e.name), '`' + e.id + '`', (e.bases || []).join(' '), e.depth, e.rarity,
    (e.toHit || e.toDam) ? `(${e.toHit || 0},${e.toDam || 0})` : '—',
    e.ac ? '[' + e.ac + ']' : '—',
    e.pval || '—', sigilNames(e.sigils),
    e.taint ? sigilNames(e.taint) : '—', e.cost
  ]);
  return [
    banner('src/data/egos.json'), '',
    '# 改修品(エゴ)一覧', '',
    table(['名前', 'id', '対象', '深度', '稀少', '(命中,ダメージ)', 'AC', 'pval', '刻印', '汚染ファーム', '価格'], rows),
    ''
  ].join('\n');
};

pages['uniques.md'] = () => {
  const rows = D.uniques.entries.filter(visible).sort((a, b) => a.depth - b.depth).map(u => [
    esc(u.name), '`' + u.id + '`', u.base, u.depth, u.rarity,
    (u.toHit || u.toDam) ? `(${u.toHit || 0},${u.toDam || 0})` : '—',
    u.ac !== undefined ? '[' + u.ac + ']' : '—',
    u.pval || '—', sigilNames(u.sigils), u.taint ? sigilNames(u.taint) : '—', u.cost
  ]);
  return [
    banner('src/data/uniques.json'), '',
    '# 固有機材一覧', '',
    '**1ランに1個**しか存在しない ([[D-38]])。', '',
    table(['名前', 'id', '土台', '深度', '稀少', '(命中,ダメージ)', 'AC', 'pval', '刻印', '汚染ファーム', '価格'], rows),
    '', '## 由来', '',
    ...D.uniques.entries.filter(visible).map(u => `- **${u.name}** — ${u.desc}`),
    ''
  ].join('\n');
};

pages['rooms.md'] = () => {
  const fmt = list => list.filter(visible).sort((a, b) => a.depth - b.depth).map(r =>
    `### ${r.name}  \`${r.id}\`\n\n` +
    `深度 ${r.depth} 以深 / 稀少 ${r.rarity}${r.size ? ' / ' + r.size : ''}  \n` +
    `${r.desc || ''}\n\n` +
    '```\n' + r.map.join('\n') + '\n```\n');
  return [
    banner('src/data/rooms.json + src/data/vaults.json'), '',
    '# 区画テンプレートと封鎖区画', '',
    '記号: `#`構造材 `.`床 `,`暗い床 `+`扉 `^`設備障害 `*`アイテム `&`良質 `9`敵 `8`強敵', '',
    '## 区画テンプレート', '',
    ...fmt(D.rooms.entries),
    '## 封鎖区画 (Vault)', '',
    '中身は深度 +10(小) / +20(大) で抽選する (docs/02 §2.4)。', '',
    ...fmt(D.vaults.entries)
  ].join('\n');
};

pages['README.md'] = () => [
  banner('src/data/*.json'), '',
  '# 参照表', '',
  '**このディレクトリは生成物です。手で編集しないでください。**', '',
  '正本は [`src/data/*.json`](../../src/data/)。生成は `node tools/gen_reference.js`。',
  '運用ルールは [docs/06-doc-rules.md](../06-doc-rules.md) §6.1 / §6.7。', '',
  table(['ファイル', '内容', '正本'], [
    ['[敵一覧](monsters.md)', '全敵の深度・HP・攻撃・警戒度', '`monsters.json` `monster-base.json`'],
    ['[アイテム一覧](items.md)', '全アイテムの深度・重量・効果・価格', '`items.json` `item-base.json`'],
    ['[系統](lineages.md)', '能力値補正・HD・技能・フラグ', '`lineages.json`'],
    ['[ロール](roles.md)', 'サブシステム・技能・能力値優先', '`roles.json`'],
    ['[能力一覧](abilities.md)', '必要Lv・コスト・失敗率・効果', '`abilities.json`'],
    ['[刻印一覧](sigils.md)', 'ルーン式鑑定の単位', '`sigils.json`'],
    ['[改修品一覧](egos.md)', 'エゴの刻印と数値', '`egos.json`'],
    ['[固有機材一覧](uniques.md)', '1ランに1個の固有装備', '`uniques.json`'],
    ['[区画テンプレート](rooms.md)', '部屋と Vault の実マップ', '`rooms.json` `vaults.json`']
  ]),
  '', `生成時の spoiler level: ${SPOILER} (1=基本 / 2=標準 / 3=完全)`, ''
].join('\n');

/* ---------- 出力 ---------- */

fs.mkdirSync(OUT_DIR, { recursive: true });
let changed = 0, wrote = 0;

for (const [name, build] of Object.entries(pages)) {
  const body = build().replace(/\r\n/g, '\n');
  const file = path.join(OUT_DIR, name);
  const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;

  if (CHECK) {
    if (old !== body) { console.log('FAIL: docs/reference/' + name + ' が古い'); changed++; }
  } else {
    if (old !== body) { fs.writeFileSync(file, body, 'utf8'); wrote++; }
  }
}

if (CHECK) {
  console.log(changed === 0
    ? 'OK: docs/reference は最新'
    : changed + ' 件が古い。node tools/gen_reference.js を実行すること');
  process.exit(changed ? 1 : 0);
}
console.log(`generated ${Object.keys(pages).length} pages (${wrote} updated) -> docs/reference/`);
